import type { Metadata } from "next";
import { getTranslations } from "next-intl/server";
import { useTranslations } from "next-intl";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { routing } from "@/i18n/routing";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "metadata.terms" });

  return {
    title: t("title"),
    description: t("description"),
    openGraph: {
      title: t("ogTitle"),
      description: t("ogDescription"),
      url: "/terminos-y-condiciones",
    },
    alternates: { canonical: "/terminos-y-condiciones" },
  };
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default function TermsPage() {
  const t = useTranslations("terms");

  return (
    <>
      <Nav sectionLinks={[]} />

      <main id="top">
        <section className="sec sec-paper" style={{ paddingTop: 160 }}>
          <div className="wrap legal-wrap">
            <div className="legal-header">
              <h1>{t("title")}</h1>
              <p className="legal-updated">{t("lastUpdated")}: August 10, 2026 &middot; Effective date: August 10, 2026</p>
            </div>

            <div className="legal-body">
              <p>These Terms of Service (the &quot;Terms&quot;) are a legally binding agreement between MUUD SpA, a company organized under the laws of Chile, Chilean tax ID (RUT) 77.634.166-5, with its registered office at Av. Presidente Kennedy 5600, Of. 507, Vitacura, Santiago, Chile (&quot;MUUD&quot;, &quot;we&quot;, &quot;us&quot; or &quot;our&quot;), and the party accessing or using the Services (as defined below).</p>
              <p>MUUD operates the website https://muud.app (the &quot;Site&quot;), the MUUD mobile and web applications (the &quot;App&quot;), and related products and services that reference these Terms (collectively, the &quot;Services&quot;). The Services are a student wellbeing platform through which educational institutions enable students and educators to complete check-ins, keep a personal journal, access wellbeing content, and give school staff visibility and early alerts to support healthy school communities.</p>
              <p><strong>IMPORTANT:</strong> The Services are provided primarily to schools and other organizations under a written subscription agreement. Students and other minors may only use the Services through an educational institution that has contracted with MUUD and in accordance with Section 3. Children may not create individual accounts on their own.</p>

              <h2>Summary of Key Points</h2>
              <p>This summary is provided for convenience only and does not replace the full Terms.</p>
              <ul>
                <li>(a) Schools own and control the Student Data processed through the Services; MUUD processes it only to provide the Services, under the school&apos;s instructions and a Data Processing Addendum.</li>
                <li>(b) MUUD does not sell personal data, does not show advertising within the Services, and does not use Student Data for targeted advertising or for profiling unrelated to the Services.</li>
                <li>(c) Minors access the Services only through their school, with consent obtained as required by the law of their country.</li>
                <li>(d) The Services are an educational wellbeing tool. They are not a medical, clinical, diagnostic or emergency service.</li>
                <li>(e) You can contact us, and exercise your privacy rights, using the details in Section 24.</li>
              </ul>

              <nav className="legal-toc">
                <h3>Contents</h3>
                <ol>
                  <li>Definitions</li>
                  <li>Structure of the Agreement; Who These Terms Apply To</li>
                  <li>Eligibility; Use by Children and Adolescents</li>
                  <li>Privacy and Data Protection</li>
                  <li>Ownership and Use of Customer Data and Student Data</li>
                  <li>FERPA and U.S. Student Privacy</li>
                  <li>Accounts and Registration</li>
                  <li>Subscriptions, Fees and Payment</li>
                  <li>License to Use the Services; Restrictions</li>
                  <li>Acceptable Use</li>
                  <li>User Content</li>
                  <li>Intellectual Property</li>
                  <li>Third-Party Services and Links</li>
                  <li>Wellbeing Disclaimer; Not a Medical or Emergency Service</li>
                  <li>Term, Suspension and Termination; Data Return and Deletion</li>
                  <li>Warranties and Disclaimers</li>
                  <li>Limitation of Liability</li>
                  <li>Indemnification</li>
                  <li>Changes to the Services and to These Terms</li>
                  <li>Governing Law and Dispute Resolution</li>
                  <li>Jurisdiction-Specific Terms</li>
                  <li>Electronic Communications</li>
                  <li>General Provisions</li>
                  <li>Contact</li>
                </ol>
              </nav>

              <h2>1. Definitions</h2>
              <p>&quot;Institutional Customer&quot; (or &quot;Customer&quot;) means the school, school district, network of schools, company, non-profit or other organization that has entered into a subscription agreement, order form or purchase order with MUUD for the provision of the Services (each, an &quot;Order&quot;).</p>
              <p>&quot;Authorized User&quot; means an individual authorized by an Institutional Customer to use the Services under the Customer&apos;s subscription, including students, teachers, school counselors, school leadership staff and, where enabled by the Customer, parents or legal guardians.</p>
              <p>&quot;Individual User&quot; means a natural person of legal age who uses the Services in their own capacity and not through an Institutional Customer.</p>
              <p>&quot;Student Data&quot; means personal data of a student (including any content a student creates in the Services, such as check-in responses and journal entries) that is processed through the Services under an Institutional Customer&apos;s subscription. Student Data includes &quot;education records&quot; as defined by FERPA (United States), &quot;personal data&quot; as defined by the GDPR, LGPD, Chilean Law No. 21.719 and the India DPDP Act, and equivalent concepts under other Applicable Data Protection Laws.</p>
              <p>&quot;Customer Data&quot; means all data, including Student Data and personal data of other Authorized Users, submitted to the Services by or on behalf of an Institutional Customer or its Authorized Users.</p>
              <p>&quot;Applicable Data Protection Laws&quot; means all data protection and privacy laws that apply to the processing of personal data under these Terms, including, as applicable: Regulation (EU) 2016/679 (&quot;GDPR&quot;) and the UK GDPR; Spanish Organic Law 3/2018 (&quot;LOPDGDD&quot;); Brazilian Law No. 13.709/2018 (&quot;LGPD&quot;); Chilean Law No. 19.628 and Law No. 21.719; the U.S. Family Educational Rights and Privacy Act (&quot;FERPA&quot;), the Children&apos;s Online Privacy Protection Act (&quot;COPPA&quot;), the Protection of Pupil Rights Amendment (&quot;PPRA&quot;) and applicable U.S. state student privacy laws (including California&apos;s SOPIPA and Ed. Code 49073.1); Mexico&apos;s Federal Law on the Protection of Personal Data Held by Private Parties; Colombia&apos;s Law 1581 of 2012; Peru&apos;s Law No. 29733; Argentina&apos;s Law No. 25.326; and India&apos;s Digital Personal Data Protection Act, 2023 and the DPDP Rules, 2025.</p>
              <p>&quot;DPA&quot; means the Data Processing Addendum entered into between MUUD and an Institutional Customer, which forms part of the agreement between MUUD and that Customer.</p>

              <h2>2. Structure of the Agreement; Who These Terms Apply To</h2>
              <p>2.1 <strong>Institutional Customers.</strong> If you are an Institutional Customer, your use of the Services is governed by (in order of precedence in case of conflict): (a) your Order; (b) the DPA; and (c) these Terms. The person accepting these Terms on behalf of an organization represents that they have authority to bind that organization.</p>
              <p>2.2 <strong>Authorized Users.</strong> If you use the Services through an Institutional Customer, these Terms govern your access to and use of the Services, but the processing of your personal data is governed by the agreement between MUUD and your institution and by MUUD&apos;s Privacy Policy. Your institution, not MUUD, decides which features are enabled for you and controls your account within the platform.</p>
              <p>2.3 <strong>Individual Users.</strong> If you use the Services as an Individual User, these Terms and the Privacy Policy govern your use directly. Individual accounts are available only to persons who have reached the age of majority in their jurisdiction, or the applicable digital consent age where an individual offering is expressly made available to older adolescents in that jurisdiction (see Section 3).</p>
              <p>2.4 <strong>Parents and guardians.</strong> Where a school enables guardian access, or where a parent or guardian provides or confirms consent for a child&apos;s use of the Services, the parent or guardian accepts these Terms on their own behalf and, to the extent permitted by law, on behalf of the child.</p>
              <p>2.5 Nothing in these Terms limits any right that an Authorized User, student, parent or consumer has under mandatory applicable law, including consumer protection law and Applicable Data Protection Laws. If any provision of these Terms conflicts with a mandatory right, the mandatory right prevails for that user.</p>

              <h2>3. Eligibility; Use by Children and Adolescents</h2>
              <p>3.1 <strong>No self-registration by children.</strong> Children may not register for the Services on their own. Accounts for students are created or provisioned only by, or at the direction of, an Institutional Customer, or with the verifiable consent of a parent or legal guardian where required and supported.</p>
              <p>3.2 <strong>Age thresholds.</strong> For purposes of these Terms, a &quot;child&quot; is any user below the age at which the user can validly consent to the processing of their personal data in connection with information society services under the law of their jurisdiction, including: 13 in the United States (COPPA) and in EU member states that have adopted the minimum age; 14 in Spain (LOPDGDD, Art. 7); 16 in EU member states that retain the GDPR default (GDPR Art. 8); the ages set by applicable law in Brazil (LGPD Art. 14, processing of children&apos;s and adolescents&apos; data in their best interest), Chile, and other Latin American jurisdictions; and 18 in India (DPDP Act, Section 9).</p>
              <p>3.3 <strong>Consent for children&apos;s use.</strong> Where the personal data of a child will be processed through the Services: (a) in school deployments, the Institutional Customer is responsible for providing all legally required notices to parents and guardians and for obtaining, documenting and maintaining any legally required consents or authorizations, or for confirming that it may consent or authorize on the parents&apos; behalf where the law permits (for example, the COPPA &quot;school consent&quot; mechanism in the United States for use limited to the educational context); (b) MUUD will provide the Customer with the information reasonably necessary to give those notices and obtain those consents; and (c) in jurisdictions where the law requires verifiable parental or guardian consent that a school cannot provide on the parents&apos; behalf (including India under the DPDP Act and DPDP Rules, 2025), MUUD and the Customer will implement a compliant verifiable consent mechanism before any child&apos;s personal data is processed.</p>
              <p>3.4 MUUD relies on the representations of the Institutional Customer that all required notices, consents and authorizations have been obtained. If MUUD becomes aware that a child&apos;s personal data has been collected without the legally required consent or authorization, MUUD will delete that data without undue delay, subject to any legal retention obligations, and will notify the Customer.</p>
              <p>3.5 <strong>Adolescents and adult users.</strong> Users who have reached the applicable digital consent age but are still minors must have permission from a parent or guardian to use the Services where local law requires it. All other users must have full legal capacity.</p>

              <h2>4. Privacy and Data Protection</h2>
              <p>4.1 <strong>Privacy Policy.</strong> Our Privacy Policy, available at https://muud.app/politica-de-privacidad, describes what personal data we process, why, on what legal basis, for how long, with whom we share it and how data subjects can exercise their rights. The Privacy Policy is incorporated into these Terms by reference. In case of conflict between these Terms and the Privacy Policy regarding the processing of personal data, the Privacy Policy and the DPA prevail.</p>
              <p>4.2 <strong>Roles.</strong> For Student Data and other Customer Data, the Institutional Customer is the data controller (or equivalent: &quot;responsable del tratamiento&quot;, &quot;controlador&quot;, &quot;Data Fiduciary&quot; under the India DPDP Act, or the educational agency or institution under FERPA) and MUUD acts as data processor (or equivalent: &quot;encargado del tratamiento&quot;, &quot;operador&quot;, &quot;Data Processor&quot;) acting only on the Customer&apos;s documented instructions and under the DPA. For Individual Users, and for account, billing, support and website data, MUUD is the data controller.</p>
              <p>4.3 <strong>Our commitments regarding Student Data.</strong> Regardless of jurisdiction, MUUD: (a) processes Student Data only to provide, maintain, secure and improve the Services for the Customer, and for no other purpose; (b) does not sell, rent or trade Student Data or any Customer personal data; (c) does not display third-party advertising in the student experience and does not use Student Data for advertising, marketing or behavioral targeting of any kind; (d) does not build profiles of students except as necessary to provide the contracted Services (for example, wellbeing check-in history visible to the school) and never for advertising; (e) does not track, monitor or profile children in ways prohibited by applicable law, including Section 9 of the India DPDP Act; (f) collects and processes only the data that is adequate, relevant and limited to what is necessary (data minimization); and (g) applies appropriate technical and organizational security measures, including encryption in transit and at rest, access controls, logging and regular reviews.</p>
              <p>4.4 <strong>Sensitive data.</strong> Check-in responses and journal entries may reveal information about a student&apos;s emotional state, which may qualify as sensitive personal data or special category data under Applicable Data Protection Laws (including GDPR Art. 9, LGPD Art. 5(II) and 11, Chilean Law No. 21.719, and equivalent provisions). Such data is processed only with a valid legal basis established by the Customer (or by the Individual User&apos;s explicit consent, where applicable), only for the wellbeing purposes of the Services, under heightened confidentiality and access controls, and is never used for advertising or disclosed to third parties except as instructed by the Customer, as described in the Privacy Policy, or as required by law.</p>
              <p>4.5 <strong>Subprocessors.</strong> MUUD uses vetted service providers (for example, cloud hosting) to operate the Services. A current list of subprocessors is available on request and, for Institutional Customers, is governed by the DPA, including flow-down of data protection obligations and advance notice of changes.</p>
              <p>4.6 <strong>International transfers.</strong> The Services are hosted in [INSERT HOSTING REGION(S), e.g., the United States and/or Chile]. Where personal data is transferred internationally, MUUD implements the safeguards required by Applicable Data Protection Laws, including: the European Commission&apos;s Standard Contractual Clauses and the UK Addendum or IDTA for transfers from the EEA and the UK, with transfer impact assessments where required; the ANPD&apos;s standard contractual clauses or other valid mechanisms under LGPD Arts. 33 to 36 for transfers from Brazil; and the conditions for international transfers under Chilean Law No. 21.719 and other applicable Latin American and Indian rules. MUUD does not rely on &quot;continued use&quot; of the Services as consent for international transfers.</p>
              <p>4.7 <strong>Data subject rights.</strong> Data subjects (including students, and parents or guardians acting on behalf of their children) may exercise their rights of access, rectification, erasure, restriction, objection, portability and withdrawal of consent, and the ARCO rights recognized in Latin American jurisdictions, as described in the Privacy Policy. For Student Data in school deployments, requests will be fulfilled in coordination with, and at the direction of, the Institutional Customer, which remains the point of contact for parents under FERPA and equivalent frameworks. MUUD will provide the Customer with reasonable assistance and self-service tools to review, correct, export and delete Student Data.</p>
              <p>4.8 <strong>Security incidents.</strong> MUUD will notify the affected Institutional Customer without undue delay, and in any event within 72 hours of becoming aware of a personal data breach affecting Customer Data, providing the information required by Applicable Data Protection Laws (including GDPR Arts. 33 and 34, Chilean Law No. 21.719, LGPD Art. 48 and the India DPDP framework) so the Customer can meet its own notification obligations. Where MUUD is the controller, MUUD will notify the competent authority and affected individuals as required by law.</p>
              <p>4.9 <strong>Data protection contacts.</strong> MUUD&apos;s privacy contact and, where required, Data Protection Officer can be reached at privacy@muud.app [OR INSERT DEDICATED ADDRESS]. Jurisdiction-specific contacts (including MUUD&apos;s EU/UK representative, Brazilian encarregado and India Grievance Officer, where applicable) are identified in Section 21 and in the Privacy Policy.</p>

              <h2>5. Ownership and Use of Customer Data and Student Data</h2>
              <p>5.1 <strong>Customer ownership.</strong> As between MUUD and the Institutional Customer, the Customer owns and retains all right, title and interest in and to Customer Data, including Student Data. Students (and their parents or guardians) retain all rights in the content they create, such as journal entries, subject to the school&apos;s rights under applicable education law.</p>
              <p>5.2 <strong>Limited license to MUUD.</strong> The Customer grants MUUD a limited, non-exclusive, non-transferable (except to subprocessors under the DPA), revocable license to host, process, transmit, display and create backups of Customer Data solely to the extent necessary to (a) provide and secure the Services, (b) comply with the Customer&apos;s instructions, and (c) comply with applicable law. This license terminates upon deletion of the data under Section 15. For clarity, MUUD claims no ownership of, and takes no perpetual or irrevocable license to, any Customer Data or any content created by students or other Authorized Users.</p>
              <p>5.3 <strong>De-identified and aggregated data.</strong> MUUD may create de-identified and aggregated data from Customer Data, in accordance with the de-identification standards of Applicable Data Protection Laws, and may use it to develop, evaluate and improve the Services and for research on student wellbeing, provided that such data cannot reasonably be used to identify any individual or any specific Institutional Customer and that MUUD contractually prohibits re-identification. Where applicable law treats de-identified student data more strictly (for example, certain U.S. state student privacy laws), MUUD will comply with the stricter standard.</p>
              <p>5.4 <strong>No mining for advertising.</strong> MUUD will not mine, scan or analyze Customer Data for advertising purposes or to build advertising profiles, and will not permit any third party to do so.</p>

              <h2>6. FERPA and U.S. Student Privacy (School Deployments in the United States)</h2>
              <p>6.1 <strong>School official.</strong> Where the Services are used by an educational agency or institution subject to FERPA, MUUD acts as a &quot;school official&quot; with a &quot;legitimate educational interest&quot; under 34 CFR 99.31(a)(1). MUUD (a) performs an institutional service or function for which the institution would otherwise use employees; (b) is under the direct control of the institution with respect to the use and maintenance of education records, as set out in the Order, the DPA and these Terms; (c) uses education records only for authorized purposes; and (d) does not re-disclose personal information from education records except as directed by the institution or as permitted by FERPA.</p>
              <p>6.2 <strong>Parental rights.</strong> The institution remains responsible for responding to parents&apos; requests to inspect and review education records under FERPA. MUUD will make Student Data available to the institution to enable it to comply.</p>
              <p>6.3 <strong>COPPA.</strong> For students under 13 in the United States, MUUD relies on the school&apos;s authorization as permitted by the FTC&apos;s guidance on COPPA in the educational context: the school may consent on behalf of parents to the collection of students&apos; personal information solely for the use and benefit of the school and for no commercial purpose. MUUD provides schools with the notices needed to inform parents, and parents may review, and request deletion of, their child&apos;s information through the school.</p>
              <p>6.4 <strong>State student privacy laws.</strong> MUUD complies with applicable U.S. state student data privacy laws, including SOPIPA (Cal. Bus. &amp; Prof. Code 22584) and student data privacy contracting statutes, and will enter into the state-required data privacy agreements where an Order so requires.</p>

              <h2>7. Accounts and Registration</h2>
              <p>7.1 You agree to provide accurate, current and complete registration information and to keep it up to date. Accounts are personal. You are responsible for maintaining the confidentiality of your credentials and for activity under your account, except where the activity results from MUUD&apos;s failure to maintain reasonable security or where mandatory law provides otherwise.</p>
              <p>7.2 Notify us promptly at soporte@muud.app of any unauthorized use of your account. Institutional Customers are responsible for managing Authorized User provisioning and de-provisioning through the administrative tools provided.</p>
              <p>7.3 We may reclaim or require a change to a username that is unlawful, offensive or infringes third-party rights.</p>

              <h2>8. Subscriptions, Fees and Payment</h2>
              <p>8.1 <strong>Institutional subscriptions.</strong> Fees, subscription periods, user counts, renewal and payment terms for Institutional Customers are set out in the applicable Order. Unless the Order states otherwise, fees are invoiced annually in advance, are stated exclusive of taxes, and each party bears the taxes for which it is legally responsible. VAT, withholding and similar taxes will be applied as required by the law of the invoicing jurisdiction.</p>
              <p>8.2 <strong>Individual purchases.</strong> Where individual paid plans are offered, we accept the payment methods displayed at checkout. Purchases made through the Apple App Store or Google Play are also subject to the store&apos;s terms, including its billing and cancellation mechanisms. Prices, currency and applicable taxes are displayed before you confirm the purchase. We may change prices prospectively with prior notice; changes do not affect the current paid period.</p>
              <p>8.3 <strong>Refunds and withdrawal rights.</strong> Except where the applicable Order provides otherwise, fees are non-refundable to the extent permitted by law. Nothing in these Terms excludes statutory withdrawal, cooling-off or refund rights that cannot be waived, including rights of consumers in the European Union and the United Kingdom (where a consumer may lose the withdrawal right for digital content only with prior express consent and acknowledgement), under Chilean Law No. 19.496, under Brazilian consumer law (CDC Art. 49), and under other applicable consumer protection laws. Purchases through app stores follow the refund policies of Apple or Google in addition to your statutory rights.</p>
              <p>8.4 <strong>Late payment.</strong> If undisputed fees remain unpaid after written notice and a reasonable cure period of at least 15 days, MUUD may suspend the affected subscription until payment is received. MUUD will not delete Customer Data solely because of late payment before the retention periods in Section 15 have elapsed.</p>

              <h2>9. License to Use the Services; Restrictions</h2>
              <p>9.1 <strong>License.</strong> Subject to these Terms and, for Institutional Customers, the applicable Order, MUUD grants you a limited, non-exclusive, non-transferable, revocable license to access and use the Services, and to install and use the App on devices you own or control, for the intended purposes of the Services: internal educational and organizational use for Institutional Customers and Authorized Users, and personal, non-commercial use for Individual Users.</p>
              <p>9.2 <strong>Restrictions.</strong> Except as permitted by mandatory law (including lawful reverse engineering for interoperability where such right cannot be excluded), you must not: (a) copy, modify, translate or create derivative works of the Services; (b) reverse engineer, decompile or disassemble the Services; (c) rent, lease, sell, sublicense, distribute or otherwise make the Services available to third parties outside your organization; (d) remove or alter proprietary notices; (e) use the Services to build a competing product; (f) access the Services by automated means (bots, scraping) without our written permission; or (g) circumvent security or usage limits.</p>
              <p>9.3 <strong>App store terms.</strong> For Apps downloaded from the Apple App Store or Google Play, the applicable store terms also apply; Apple and Google are third-party beneficiaries of this Section with the right to enforce it, are not responsible for the App or its support, and your license is limited to use on devices running the applicable operating system as permitted by the store&apos;s usage rules.</p>

              <h2>10. Acceptable Use</h2>
              <p>10.1 You agree to use the Services only for their intended purposes and in compliance with applicable law. Without limiting the foregoing, you must not: use the Services to harass, bully, threaten, defame or harm any person; upload content that is unlawful, discriminatory, sexually explicit, violent or otherwise harmful, in particular content harmful to minors; impersonate any person; upload malware or interfere with the integrity or performance of the Services; attempt unauthorized access to accounts, systems or data; collect other users&apos; personal data without authorization; send spam or unsolicited communications through the Services; or use the Services in violation of export control or sanctions laws.</p>
              <p>10.2 Institutional Customers are responsible for communicating acceptable use rules to their Authorized Users and for addressing misconduct by their users in accordance with their own policies, in coordination with MUUD where needed.</p>
              <p>10.3 We may investigate suspected violations and take proportionate measures, including removing content, restricting features or suspending accounts, in accordance with Section 15 and applicable law, including, where applicable, the notice and redress requirements of platform regulation.</p>

              <h2>11. User Content</h2>
              <p>11.1 <strong>Your content.</strong> &quot;User Content&quot; means content that users create or upload in the Services, such as journal entries, check-in responses, comments and messages. You (or, for Student Data, the student and the Institutional Customer as applicable) retain all rights in User Content. MUUD claims no ownership of User Content.</p>
              <p>11.2 <strong>License to operate the Services.</strong> You grant MUUD a limited, non-exclusive, worldwide, royalty-free license to host, store, reproduce, transmit, display and back up User Content solely as necessary to operate, provide, secure and support the Services for you and, where applicable, your institution. This license is revocable and ends when the User Content is deleted from the Services in accordance with these Terms and the DPA, except for lawful backups pending deletion and content we must retain by law. MUUD does not acquire any perpetual or irrevocable license over User Content and does not use User Content for advertising, publication, resale or any purpose unrelated to the Services.</p>
              <p>11.3 <strong>Journal privacy.</strong> Personal journal entries are private to the user by default. The visibility of any student content to school staff is determined by the feature design disclosed to the Customer and in the Privacy Policy (for example, wellbeing check-in results and alerts visible to designated staff), and never extends beyond what is necessary for the wellbeing purposes of the Services.</p>
              <p>11.4 <strong>Feedback.</strong> If you voluntarily send us suggestions or feedback about the Services, you grant MUUD a non-exclusive, perpetual, irrevocable, royalty-free license to use that feedback to improve the Services, without obligation to you. Feedback does not include personal data or User Content, and this Section does not apply to content created by children.</p>
              <p>11.5 <strong>Responsibility.</strong> You are responsible for your User Content and represent that it does not infringe third-party rights or violate applicable law. We may remove or restrict access to User Content that violates these Terms or applicable law, applying the safeguards in Section 10.3.</p>

              <h2>12. Intellectual Property</h2>
              <p>12.1 The Services, including software, source code, databases, design, text, graphics, audio, video and MUUD&apos;s trademarks and logos (excluding Customer Data and User Content), are owned by MUUD or its licensors and are protected by intellectual property laws in Chile and internationally. Except for the licenses expressly granted in these Terms, no rights are granted to you, and MUUD reserves all rights.</p>
              <p>12.2 <strong>Copyright complaints.</strong> If you believe content on the Services infringes your copyright, notify us at soporte@muud.app with sufficient detail to identify the work, the allegedly infringing material and your contact information. We will process notices in accordance with applicable law and may remove infringing material and terminate repeat infringers.</p>

              <h2>13. Third-Party Services and Links</h2>
              <p>13.1 The Services may interoperate with third-party services enabled by you or your institution (for example, single sign-on providers). Your use of a third-party service is governed by that third party&apos;s terms and privacy policy. For Institutional Customers, MUUD will only integrate third-party services with Customer Data as permitted by the DPA.</p>
              <p>13.2 The Services may contain links to third-party websites. MUUD does not control and is not responsible for third-party websites or content. Access them at your own discretion.</p>

              <h2>14. Wellbeing Disclaimer; Not a Medical or Emergency Service</h2>
              <p>14.1 The Services are an educational wellbeing platform. They are not, and must not be used as, a medical device, a clinical, diagnostic, psychological, psychiatric or therapeutic service, or a substitute for professional advice, diagnosis or treatment. MUUD does not provide medical or mental health care and makes no representation that use of the Services will produce any particular wellbeing outcome.</p>
              <p>14.2 Alerts and check-in visualizations are informational tools to help trained school staff prioritize human follow-up. They are not clinical assessments, and the absence of an alert is not an indication that a student does not need support. Decisions about student support remain the responsibility of the Institutional Customer and its qualified staff.</p>
              <p>14.3 <strong>Emergencies.</strong> The Services are not monitored in real time by MUUD and must not be used to report emergencies. If you or someone else is in danger or experiencing a crisis, contact local emergency services or a crisis line immediately.</p>

              <h2>15. Term, Suspension and Termination; Data Return and Deletion</h2>
              <p>15.1 <strong>Term.</strong> For Institutional Customers, the term is set out in the Order. For other users, these Terms apply while you use the Services.</p>
              <p>15.2 <strong>Suspension.</strong> MUUD may suspend an account or access where reasonably necessary to (a) address a security risk or legal violation, (b) comply with law or a binding order, or (c) address material breach of these Terms that remains uncured after notice, except where prior notice is not reasonably possible. Suspension will be proportionate, limited in scope and duration, and MUUD will restore access once the cause is resolved. MUUD will not terminate or suspend arbitrarily or without cause and will state the reasons on request, subject to legal restrictions.</p>
              <p>15.3 <strong>Termination by you.</strong> Individual Users may stop using the Services and delete their account at any time through in-product settings or by using the deletion form at https://muud.app (Legal, Delete account) or by writing to soporte@muud.app. Institutional Customers may terminate as provided in the Order.</p>
              <p>15.4 <strong>Data return and deletion.</strong> Upon expiration or termination of an Institutional Customer&apos;s subscription, MUUD will (a) make Customer Data available for export in a commonly used, machine-readable format for at least 60 days, and (b) thereafter delete Customer Data from production systems within 90 days and from backups within the backup cycle, unless retention is required by law, in each case certifying deletion on request. During the subscription, the Customer can delete Student Data at any time using the administrative tools or by written instruction. For Individual Users, account deletion removes personal data in accordance with the Privacy Policy.</p>
              <p>15.5 Inactive free accounts of Individual Users may be deleted after 24 months of inactivity, with at least 30 days&apos; prior notice to the account email, consistent with data retention rules under Applicable Data Protection Laws, including the erasure-on-inactivity provisions of the India DPDP Rules where applicable. Student accounts under an institutional subscription are managed by the Institutional Customer and are not subject to automatic inactivity deletion without the Customer&apos;s instruction.</p>

              <h2>16. Warranties and Disclaimers</h2>
              <p>16.1 MUUD warrants to Institutional Customers that the Services will perform materially in accordance with the applicable documentation and that MUUD will provide the Services with reasonable skill and care and in compliance with Applicable Data Protection Laws that apply to MUUD as processor.</p>
              <p>16.2 Except as expressly stated in these Terms or an Order, and to the maximum extent permitted by applicable law, the Services are provided &quot;as is&quot; and &quot;as available&quot;, and MUUD disclaims implied warranties of merchantability, fitness for a particular purpose and non-infringement. We do not warrant uninterrupted or error-free operation.</p>
              <p>16.3 <strong>Consumer rights preserved.</strong> If you use the Services as a consumer, you retain all warranties, guarantees and remedies granted by mandatory consumer law in your country of residence (including the legal guarantee regimes of the EU, Chile&apos;s Law No. 19.496, Brazil&apos;s CDC and equivalent laws), and nothing in this Section limits them.</p>

              <h2>17. Limitation of Liability</h2>
              <p>17.1 Nothing in these Terms excludes or limits liability that cannot be excluded or limited under applicable law, including liability for (a) willful misconduct or gross negligence, (b) death or personal injury caused by negligence, (c) fraud, and (d) any liability to consumers or data subjects that mandatory law does not permit to be limited.</p>
              <p>17.2 Subject to Section 17.1, neither party will be liable for indirect, incidental, special, consequential or punitive damages, or for loss of profits or revenue, arising out of or related to these Terms.</p>
              <p>17.3 Subject to Sections 17.1 and 17.2, each party&apos;s total aggregate liability arising out of or related to these Terms will not exceed the fees paid or payable to MUUD in the 12 months preceding the event giving rise to liability. For breaches by MUUD of its confidentiality or data protection obligations under the DPA, a higher cap may be agreed in the Order, and any such cap does not limit data subjects&apos; own statutory claims.</p>
              <p>17.4 This Section allocates risk between MUUD and Institutional Customers and applies to Individual Users only to the extent permitted by the consumer law of their residence.</p>

              <h2>18. Indemnification</h2>
              <p>18.1 <strong>By Institutional Customers.</strong> An Institutional Customer will defend and indemnify MUUD against third-party claims arising from (a) Customer Data or the Customer&apos;s instructions violating applicable law or third-party rights, or (b) the Customer&apos;s failure to obtain legally required consents or authorizations under Section 3, except to the extent caused by MUUD&apos;s breach of these Terms or the DPA.</p>
              <p>18.2 <strong>By MUUD.</strong> MUUD will defend and indemnify the Institutional Customer against third-party claims alleging that the Services, as provided by MUUD and used as permitted, infringe intellectual property rights, and will remedy any established infringement by procuring rights, modifying the Services or refunding prepaid unused fees.</p>
              <p>18.3 No indemnification obligations are imposed on Individual Users, students, parents or guardians beyond their liability under applicable law.</p>

              <h2>19. Changes to the Services and to These Terms</h2>
              <p>19.1 We continuously improve the Services and may add, change or remove features, provided that during a paid subscription we will not materially degrade the core functionality contracted.</p>
              <p>19.2 We may update these Terms. For material changes, we will give at least 30 days&apos; prior notice by email and/or in-product notice before the changes take effect, identifying the changes. If you do not agree, you may terminate before the effective date; for prepaid subscriptions materially and adversely affected, the Customer may terminate and receive a pro-rata refund of unused prepaid fees. Continued use after the effective date constitutes acceptance only where such acceptance is valid under applicable law. Changes required by law or addressing security may take effect sooner, with notice as promptly as possible. The applicable version and its date will always be published on the Site, and prior versions are available on request.</p>

              <h2>20. Governing Law and Dispute Resolution</h2>
              <p>20.1 <strong>Institutional Customers.</strong> Unless the Order states otherwise, these Terms are governed by the laws of Chile, and the courts of Santiago, Chile have exclusive jurisdiction, except that either party may seek injunctive relief for intellectual property or confidentiality breaches in any competent court.</p>
              <p>20.2 <strong>Consumers.</strong> If you use the Services as a consumer, you benefit from the mandatory protections of the law of your country of habitual residence, and you may bring claims before the courts of that country. MUUD may bring claims against a consumer only in the courts of the consumer&apos;s residence. Nothing in these Terms deprives consumers of access to local consumer protection authorities (for example, SERNAC in Chile, PROCON in Brazil, or EU consumer bodies and the EU Online Dispute Resolution platform where applicable).</p>
              <p>20.3 <strong>Data protection claims.</strong> Nothing in this Section limits the right of any data subject to lodge a complaint with a supervisory authority (including any EU/EEA supervisory authority, the Spanish AEPD, Brazil&apos;s ANPD, Chile&apos;s Agencia de Proteccion de Datos Personales, or India&apos;s Data Protection Board) or to seek judicial remedies under Applicable Data Protection Laws.</p>
              <p>20.4 <strong>Good-faith resolution.</strong> Before starting formal proceedings, the parties will attempt in good faith to resolve disputes through the contacts in Section 24 for at least 30 days, except for urgent relief.</p>

              <h2>21. Jurisdiction-Specific Terms</h2>
              <h3>21.1 European Economic Area, United Kingdom and Switzerland</h3>
              <p>Processing of personal data is subject to the GDPR, the UK GDPR and the Swiss FADP, as applicable. The digital consent age is the age set by the member state of the user&apos;s residence (between 13 and 16; GDPR Art. 8). International transfers are protected as described in Section 4.6. Where required by GDPR Art. 27 or UK GDPR Art. 27, MUUD&apos;s EU and UK representatives are identified in the Privacy Policy: [INSERT EU REPRESENTATIVE] and [INSERT UK REPRESENTATIVE]. Consumers in the EU/UK retain their statutory withdrawal and digital content conformity rights.</p>
              <h3>21.2 Spain</h3>
              <p>In addition to the GDPR, the LOPDGDD applies. The digital consent age in Spain is 14 (LOPDGDD Art. 7); processing of data of children under 14 requires the consent of the holders of parental authority or guardianship, or another valid legal basis established by the school in accordance with Spanish education and data protection rules. The AEPD is the supervisory authority.</p>
              <h3>21.3 Brazil</h3>
              <p>The LGPD applies. Personal data of children and adolescents is processed in their best interest (LGPD Art. 14). For school deployments, the school as controller establishes the legal basis and, where consent is required, obtains the specific and highlighted consent of at least one parent or legal guardian; MUUD provides supporting mechanisms and information. MUUD does not condition participation in activities on the provision of data beyond what is necessary. MUUD&apos;s encarregado (data protection officer contact) for Brazil is identified in the Privacy Policy. Data subjects may petition the ANPD. Brazilian consumers retain their rights under the Consumer Defense Code, including Art. 49 withdrawal for distance purchases.</p>
              <h3>21.4 Chile</h3>
              <p>Processing is currently subject to Law No. 19.628 and, as from December 1, 2026, to Law No. 21.719, including its principles, the full set of ARCO rights plus portability, security and breach notification duties, rules for processing sensitive data and data of children and adolescents (processed in their best interest and with the consents the law requires), and the oversight of the Agencia de Proteccion de Datos Personales. Consumers retain their rights under Law No. 19.496. These Terms are intended to be read consistently with Law No. 21.719 as of its entry into force.</p>
              <h3>21.5 Other Latin American Jurisdictions</h3>
              <p>In Mexico, the Federal Law on the Protection of Personal Data Held by Private Parties applies, including ARCO rights and privacy notice requirements. In Colombia, Law 1581 of 2012 and Decree 1377 of 2013 apply, including the requirement that processing of minors&apos; data respect their best interest and fundamental rights and the authorization regime supervised by the SIC. In Peru, Law No. 29733 and its regulations apply, supervised by the ANPD Peru. In Argentina, Law No. 25.326 applies, supervised by the AAIP. Where the Services are provided in any other jurisdiction, MUUD complies with the applicable local data protection framework, and mandatory local rules prevail over any conflicting provision of these Terms.</p>
              <h3>21.6 United States</h3>
              <p>In addition to Section 6 (FERPA and COPPA), MUUD complies with the PPRA in respect of survey-type content where applicable, and with applicable state student privacy laws, including prohibitions on targeted advertising to students, on selling student data and on non-educational profiling (for example, SOPIPA). For California consumers, applicable rights under the CCPA/CPRA are described in the Privacy Policy; MUUD does not sell or share personal information as those terms are defined by the CCPA. California users may also contact the Complaint Assistance Unit of the California Department of Consumer Affairs at 1625 North Market Blvd., Suite N 112, Sacramento, California 95834, or by telephone at (800) 952-5210.</p>
              <h3>21.7 India</h3>
              <p>The Digital Personal Data Protection Act, 2023 and the DPDP Rules, 2025 apply. For users in India: (a) any person under 18 is a child, and MUUD, together with the Institutional Customer, will ensure that verifiable consent of a parent or lawful guardian is obtained in the manner required by Rule 10 before processing a child&apos;s personal data, except to the extent a statutory exemption applies to processing by or for educational institutions; (b) MUUD does not undertake tracking or behavioural monitoring of children or targeted advertising directed at children; (c) notices and consent requests will meet the requirements of the Act and Rules, and consent may be withdrawn as easily as it was given; (d) personal data breaches will be notified to the Data Protection Board of India and affected Data Principals as required; and (e) MUUD&apos;s Grievance Officer for India can be contacted at [INSERT GRIEVANCE OFFICER NAME AND EMAIL], and Data Principals may escalate to the Data Protection Board of India.</p>

              <h2>22. Electronic Communications</h2>
              <p>You consent to receive communications from us electronically (email and in-product notices), and you agree that such communications satisfy any legal requirement of written form, to the extent permitted by law. You may request legally required communications on paper where the law grants that right. Electronic acceptance of these Terms and of Orders is valid in accordance with applicable electronic signature laws, including Chilean Law No. 19.799.</p>

              <h2>23. General Provisions</h2>
              <p>23.1 <strong>Entire agreement.</strong> These Terms, the Privacy Policy and, for Institutional Customers, the Order and DPA constitute the entire agreement regarding the Services and supersede prior agreements on the same subject.</p>
              <p>23.2 <strong>Assignment.</strong> You may not assign these Terms without our prior written consent. MUUD may assign these Terms to an affiliate or in connection with a merger, acquisition or sale of assets, provided the assignee assumes all obligations, including data protection obligations, and Institutional Customers are given prior notice; in the event of a change of control, protections applicable to Student Data continue to apply or the Customer may terminate and require deletion of Customer Data.</p>
              <p>23.3 <strong>Severability; waiver.</strong> If any provision is held unenforceable, the remainder remains in effect and the provision will be enforced to the maximum extent permissible. Failure to enforce a provision is not a waiver.</p>
              <p>23.4 <strong>Force majeure.</strong> Neither party is liable for delay or failure caused by events beyond its reasonable control, except for payment obligations.</p>
              <p>23.5 <strong>Independent parties.</strong> The parties are independent contractors. These Terms create no partnership, joint venture, employment or agency relationship.</p>
              <p>23.6 <strong>Language.</strong> These Terms are drafted in English. Where the law of your jurisdiction requires that consumer or data protection information be provided in a local language (for example, Spanish or Portuguese), the local language version published by MUUD applies, and in case of discrepancy the version most protective of the user prevails to the extent required by mandatory law; otherwise the English version controls.</p>
              <p>23.7 <strong>Survival.</strong> Sections that by their nature should survive termination (including 4, 5, 11.4, 12, 15.4, 16 to 18, 20 and 23) survive.</p>

              <h2>24. Contact</h2>
              <p>
                MUUD SpA<br />
                Av. Presidente Kennedy 5600, Of. 507, Vitacura, Santiago, Chile<br />
                General support: soporte@muud.app | Tel: +56 9 2691 3974<br />
                Privacy and data protection: privacy@muud.app
              </p>

              <p style={{ marginTop: 48, color: "var(--muted)", fontSize: "0.9rem" }}>&copy; 2026 MUUD SpA. All rights reserved.</p>
            </div>
          </div>
        </section>
      </main>

      <Footer variant="general" />
    </>
  );
}
